### ISSUE TITLE
建议从repo中删去pdf

### ISSUE THREAD

**Issue by inkydragon** [latexstudio/LaTeXPackages-CN#13]
如题，由于有TeX源文件，pdf等二进制文件放在repo里就显得多余，如果需要发布二进制文件可以放在release里。另外由于每次编译出的pdf的hash均不相同，git就需要单独储存这些pdf，这样会导致repo越来越大，不便于clone。

**Comment by latexstudio** [comment]
现在 24M 左右，后面变大了，会慢慢调整。感谢反馈！
