### ISSUE TITLE
Metapost 翻译计划

### ISSUE THREAD

**Issue by inkydragon** [latexstudio/LaTeXPackages-CN#5]
详细介绍见[Metapost-readme](https://github.com/latexstudio/LaTeXPackages-CN/tree/master/metapost)

这里用作TODO-list以及任务认领
### TODO-list
- [x] 上传原始文件
- [ ] 添加中文支持
- [ ] mplibapi 格式转换 (conTeXt -> LaTeX)
- [ ] 字体&格式规范
- [ ] Work-list
- [ ] check-list

---
## 需要翻译的内容
[tutorial](https://github.com/latexstudio/LaTeXPackages-CN/tree/master/metapost/tutorial)：
1. mpintro.pdf - 13页
[A Beginner’s Guide to METAPOST for Creating High-Quality Graphics](http://www.tug.org/docs/metapost/mpintro.pdf)
[manual](https://github.com/latexstudio/LaTeXPackages-CN/tree/master/metapost/manual)：
2. mpman.pdf - 113页 
[METAPOST a user’s manual](https://www.tug.org/docs/metapost/mpman.pdf)
3. mpgraph.pdf - 17页 
[Drawing Graphs with MetaPost](https://www.tug.org/docs/metapost/mpgraph.pdf)
4. mpboxes.pdf - 9页 
[Drawing Boxes with MetaPost](https://www.tug.org/docs/metapost/mpboxes.pdf)
5. mplibapi.pdf - 30页 
[MPlib API documentation](https://www.tug.org/docs/metapost/mplibapi.pdf)

## 翻译认领方法：
- 本issue下面回复 认领章节
 (建议带上预计完成的时间，这样即使鸽了，其他人也不用纠结重复翻译的问题)

### 翻译提交;
- fork项目 翻译完了push

---

### 关于错误提交
- 可以直接更正后push
- 简单的错误可以在本issue先提出然后@0u0 
我会确认后尽快修正
- 关于翻译的格式、排版 or 其他可能有争议的问题，建议新开一个issue，方便讨论
(若要新开issue，建议标题带上【metapost】)

---
## 任务认领列表
- @0u0 - 暂时负责挖坑 - (2017-02-12~填坑完毕)
- Waiting for you

**Comment by inkydragon** [comment]
发现mplibapi.tex 是 conTeXt 格式的，比较古老了，应该更新一下。

把源文件按类型分目录的尝试, 由于mpost的[bug?](https://inkydragon.github.io/zh-CN/Metapost-btex-etex-problem/) 【主要】, 以及Makefile 难写的问题，暂时放弃

**Comment by yangdawei** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已收到您的邮件。
